---

version: '3.4'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

networks:
  elk-core: {}
  elk-node:
    external:
      name: 'elk-node'
  services:
    external:
      name: 'services'

services:
  dejavu:
    image: "${DEJAVU_IMAGE_NAME}:${DEJAVU_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
    expose:
      - '1358'
    networks:
      - 'elk-core'
      - 'services'

  elastalert:
    image: "${ELASTALERT_IMAGE_NAME}:${ELASTALERT_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
    expose:
      - '3030'
      - '3333'
    networks:
      - 'elk-core'
    volumes:
      - 'elastalert_data:/opt/elastalert/server_data'
      - './elastalert/config/config.json:/opt/elastalert/config.json'
      - './elastalert/config/config.yaml:/opt/elastalert/config.yaml'
      - './elastalert/rules:/opt/elastalert/rules'
      - './elastalert/rule_templates:/opt/elastalert/rule_templates'

  elastichq:
    image: "${ELASTICHQ_IMAGE_NAME}:${ELASTICHQ_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
    environment:
      HQ_DEFAULT_URL: 'http://elasticsearch:9200'
    expose:
      - '5000'
    networks:
      - 'elk-core'
      - 'services'
    volumes:
      - 'elastichq_data:/src/db'

  elasticsearch:
    build:
      context: './elasticsearch/'
      args:
        ELK_VERSION: "${ELK_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    env_file:
      - './env/elasticsearch.env'
    networks:
      - 'elk-core'
      - 'elk-node'
      - 'services'
    ports:
      - "${LISTEN_IP_ADDRESS}:9200:9200"
      - "${LISTEN_IP_ADDRESS}:9300:9300"
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - 'elasticsearch_data:/usr/share/elasticsearch/data'

  elasticsearch_exporter:
    image: "${ELASTICSEARCH_EXPORTER_IMAGE_NAME}:${ELASTICSEARCH_EXPORTER_IMAGE_VERSION}"
    command:
      - '--es.uri=http://elasticsearch:9200'
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
    networks:
      - 'elk-core'
    ports:
      - "${LISTEN_IP_ADDRESS}:9108:9108"

  logstash:
    build:
      context: './logstash/'
      args:
        ELK_VERSION: "${ELK_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
    env_file:
      - './env/logstash.env'
    networks:
      - 'elk-core'
      - 'elk-node'
      - 'services'
    ports:
      - "${LISTEN_IP_ADDRESS}:5000:5000"
      - "${LISTEN_IP_ADDRESS}:6000:6000"
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro'
      - './logstash/pipeline:/usr/share/logstash/pipeline:ro'

  kibana:
    build:
      context: './kibana/'
      args:
        ELK_VERSION: "${ELK_VERSION}"
        KIBANA_PLUGIN_ELASTALERT_VERSION: "${KIBANA_PLUGIN_ELASTALERT_VERSION}"
        KIBANA_PLUGIN_ENHANCED_TABLE_VERSION: "${KIBANA_PLUGIN_ENHANCED_TABLE_VERSION}"
        KIBANA_PLUGIN_LOGTRAIL_VERSION: "${KIBANA_PLUGIN_LOGTRAIL_VERSION}"
        KIBANA_PLUGIN_WAZUH_VERSION: "${KIBANA_PLUGIN_WAZUH_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
      - 'logstash'
    expose:
      - '5601'
    networks:
      - 'elk-core'
      - 'elk-node'
      - 'services'
    ports:
      - "${LISTEN_IP_ADDRESS}:5601:5601"
    volumes:
      - './kibana/config/:/usr/share/kibana/config:ro'

  wazuh:
    image: "${WAZUH_IMAGE_NAME}:${WAZUH_IMAGE_VERSION}"
    restart: 'unless-stopped'
    logging: *default-logging
    depends_on:
      - 'elasticsearch'
      - 'logstash'
    env_file:
      - './env/wazuh.env'
    expose:
      - '514/udp'
      - '1514/udp'
      - '1515/tcp'
      - '1516/tcp'
      - '55000/tcp'
    networks:
      elk-core:
        aliases:
          - 'elk-core.wazuh'
      elk-node:
        aliases:
          - 'elk-node.wazuh'
      services:
        aliases:
          - 'services.wazuh'
    volumes:
      - 'wazuh_filebeat_lib:/var/lib/filebeat'
      - 'wazuh_filebeat_log:/var/log/filebeat'
      - 'wazuh_ossec_data:/var/ossec/data'
      - 'wazuh_postfix_etc:/etc/postfix'

volumes:
  elastalert_data: {}
  elastichq_data: {}
  elasticsearch_data: {}
  wazuh_filebeat_lib: {}
  wazuh_filebeat_log: {}
  wazuh_ossec_data: {}
  wazuh_postfix_etc: {}
