filebeat:
 prospectors:
  - type: 'log'
    paths:
     - '/var/ossec/logs/alerts/alerts.json'
    document_type: 'json'
    json.message_key: 'log'
    json.keys_under_root: true
    json.overwrite_keys: true
    tail_files: true

output:
 logstash:
   hosts: ['logstash:6000']
