---

discovery-url: 'https://auth.example.com/auth/realms/foobar'
client-id: 'KEYCLOAK_CLIENT_ID'
client-secret: 'KEYCLOAK_CLIENT_SECRET'
listen: '0.0.0.0:3001'
enable-refresh-tokens: false
redirection-url: 'https://logs.example.com'
encryption-key: 'VERY_SECRET_VALUE_OF_32_CHARS'
upstream-url: 'http://127.0.0.1:4181'
enable-token-header: false
enable-authorization-cookies: false
enable-refresh-tokens: true
enable-login-handler: true
http-only-cookie: true
cookie-access-name: 'sso-xxxxxx'
cookie-refresh-name: 'sso-yyyyyy'
preserve-host: true
scopes:
  - 'offline_access'
match-claims:
  aud: 'KEYCLOAK_CLIENT_ID'
  iss: 'https://keycloak.example.com/auth/realms/example'
add-claims:
  - 'name'
resources:
  - uri: '/*'
